/**
 * Regenerate the per-level physical minimum-time floors baked into the
 * leaderboard worker (backend/leaderboard/worker.mjs → MIN_TIMES).
 *
 * A run cannot average faster than the hard horizontal speed cap (dash 260 +
 * max belt drag 55 = 315 px/s) over the start→goal distance, so the true
 * minimum clear time is ~width*16/315. The floor is HALF of that — far below
 * any real run (never rejects a legit time) yet it rejects the physically
 * impossible fakes a raw-API cheater would POST. Boss arenas are tiny → the 3s
 * fallback floor.
 *
 * Run (bundles the TS level graph first, then prints the array to paste into
 * worker.mjs → MIN_TIMES):
 *   npx esbuild scripts/genMinTimes.mjs --bundle --platform=node --format=esm \
 *     --outfile=/tmp/genMinTimes.mjs && node /tmp/genMinTimes.mjs
 */
import { LEVELS } from '../src/data/levels/index.ts';
import { TUNING } from '../src/data/tuning.ts';

const MAX_H = TUNING.run.dashCap + (TUNING.belt?.speed ?? 0);
const SAFETY = 0.5;
const FALLBACK = 3000;

const floors = LEVELS.map((l) => {
  const widthPx = l.rows[0].length * 16;
  const straightLineMs = (widthPx / MAX_H) * 1000;
  return Math.round(Math.max(FALLBACK, straightLineMs * SAFETY));
});

const rows = [];
for (let i = 0; i < floors.length; i += 10) rows.push('  ' + floors.slice(i, i + 10).join(', ') + ',');
console.log(`// MAX_H=${MAX_H} px/s, SAFETY=${SAFETY} — regenerated by scripts/genMinTimes.mjs`);
console.log('const MIN_TIMES = [\n' + rows.join('\n') + '\n];');
